version: '2.1'
services:

  gourmet-db:
    image: gourmet-db:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 2s
      retries: 20
    container_name: gourmet-db

  svc-receiver:
    image: svc-receiver:latest
    environment:
    - RECEIVER_SERVICE_ADDRESS=:9091
    env_file:
    - ./config/docker/gourmet-db.env
    ports:
    - 9091:9091
    depends_on:
      gourmet-db:
        condition: service_healthy
    container_name: svc-receiver
